"""убрала коллекции из рецепта

Revision ID: 7b829db18bbb
Revises: ff8738589dc7
Create Date: 2025-09-13 21:52:47.177555

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7b829db18bbb'
down_revision = 'ff8738589dc7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
