"""удалила таблицу тегов

Revision ID: 1af4cd655f79
Revises: 0175f1463936
Create Date: 2025-07-25 14:08:18.757889

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1af4cd655f79'
down_revision = '0175f1463936'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
