"""добавила даты

Revision ID: 0d84292cd1df
Revises: 1af4cd655f79
Create Date: 2025-07-25 19:45:50.388828

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '0d84292cd1df'
down_revision = '1af4cd655f79'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
