"""изменила back_populates в user model

Revision ID: 90805dab7cf4
Revises: 9d5ac2a3f123
Create Date: 2025-09-10 20:02:18.139675

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '90805dab7cf4'
down_revision = '9d5ac2a3f123'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
