"""добавила в рецепт cooking_time

Revision ID: 8793db1f44fb
Revises: 90805dab7cf4
Create Date: 2025-09-10 20:09:29.870529

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8793db1f44fb'
down_revision = '90805dab7cf4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
