"""поменяла ингредиенты на список

Revision ID: 9d5ac2a3f123
Revises: 0d84292cd1df
Create Date: 2025-09-02 20:18:06.282445

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9d5ac2a3f123'
down_revision = '0d84292cd1df'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
